# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  use_frameworks!
  pod 'DoricCore', :path => '../../doric-iOS'
  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
