# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Example' do
  
  use_modular_headers!
  
  pod 'DoricCore', :path => '../../'
  pod 'DoricDevkit', :path => '../../'

  #pod 'YYWebImage'
  
  #pod 'YYImage/WebP'

  pod 'SDWebImage'

  pod 'SDWebImageWebPCoder'

  pod 'YYCache'

  #pod 'TMCache'
  
  pod 'PINCache'
  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            end
        end
    end
end