plugins {
    id 'com.android.library'
}
android {
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        compileSdk 35
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            consumerProguardFiles 'proguard-rules.pro'
        }
    }
    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
    namespace = "pub.doric.jse"
}

if (new File('scripts/upload.gradle').exists()) {
    apply from: rootProject.file('scripts/upload.gradle')
}
