require "json"

package = JSON.parse(File.read(File.join(__dir__, "../package.json")))
version = package['dependencies']["doric"]
version = version.gsub('^','')

source 'https://cdn.cocoapods.org/'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '__$__' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for __$__
  pod 'DoricCore', "#{version}"
  pod 'DoricDevkit', "#{version}"
  
  pod 'SDWebImage'

  pod 'SDWebImageWebPCoder'

  pod 'PINCache'

  dir_node_modules = File.join(__dir__,"../node_modules")
  Dir.foreach(dir_node_modules) do |file|
    if File.exist?(File.join(dir_node_modules, file, "__doric_library__"))
      puts "Doric Library: #{File.join(dir_node_modules, file)}"
      ret = Dir.glob(File.join(dir_node_modules,file,"*.podspec"))
      if(ret.length > 0)
        podspecPath = ret[0]
        extn = File.extname  podspecPath 
        podspecName = File.basename podspecPath, extn
        pod podspecName,  :path => File.join(dir_node_modules, file)
      end
    end
  end  
end
